package com.los.applicationservice.service.serviceImpl;

import com.los.applicationservice.dto.*;
import com.los.applicationservice.exception.ApplicationNotFoundException;
import com.los.applicationservice.kafka.KafkaProducerService;
import com.los.applicationservice.kafka.event.ApplicationAssignmentCreatedEvent;
import com.los.applicationservice.kafka.event.ApplicationAssignmentStatusChangedEvent;
import com.los.applicationservice.kafka.event.ApplicationCreatedEvent;
import com.los.applicationservice.kafka.event.ApplicationStatusChangedEvent;
import com.los.applicationservice.model.*;
import com.los.applicationservice.repository.ApplicationAssignmentRepository;
import com.los.applicationservice.repository.ApplicationRepository;
import com.los.applicationservice.repository.LoanProductRepository;
import com.los.applicationservice.repository.TaskMasterRepository;
import com.los.applicationservice.repository.TaskStageMasterRepository;
import com.los.applicationservice.service.ApplicationService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Objects;

@Service
@RequiredArgsConstructor
public class ApplicationServiceImpl implements ApplicationService {

    private final ApplicationRepository applicationRepository;
    private final ApplicationAssignmentRepository applicationAssignmentRepository;
    private final LoanProductRepository loanProductRepository;
    private final TaskMasterRepository taskMasterRepository;
    private final TaskStageMasterRepository taskStageMasterRepository;

    private final KafkaProducerService kafkaProducerService;


    // =========================================================
    // GET ALL APPLICATIONS
    // =========================================================

    @Override
    @Transactional
    public List<ApplicationResponse> getAllApplications() {

        return applicationRepository.findAll()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }


    // =========================================================
    // GET APPLICATION BY ID
    // =========================================================

    @Override
    @Transactional
    public ApplicationResponse getApplicationById(
            Long applicationId) {

        Application application =
                findApplication(applicationId);

        return mapToResponse(application);
    }


    // =========================================================
    // CREATE APPLICATION
    // =========================================================

    @Override
    @Transactional
    public ApplicationResponse createApplication(
            ApplicationRequest request) {

        LocalDateTime now = LocalDateTime.now();

        Application application = new Application();

        application.setLeadId(
                request.getLeadId());

        application.setCustomerId(
                request.getCustomerId());

        application.setLoanProduct(
                request.getLoanProduct());

        application.setLoanAmount(
                request.getLoanAmount());

        application.setLoanTenure(
                request.getLoanTenure());

        application.setInterestRate(
                request.getInterestRate());

        application.setStatus(
                ApplicationStatus.DRAFT);

        application.setDescription(
                request.getDescription());

        application.setCreatedAt(now);
        application.setModifiedAt(now);

        /*
         * applicationId is generated by PostgreSQL/JPA.
         */

        Application saved =
                applicationRepository.save(application);

        /*
         * Application number is generated after
         * the database generates the application ID.
         */
        saved.setApplicationNumber(
                "APP-" + saved.getApplicationId());

        saved.setModifiedAt(
                LocalDateTime.now());

        saved =
                applicationRepository.save(saved);


        // =====================================================
        // KAFKA - APPLICATION CREATED
        // =====================================================

        ApplicationCreatedEvent event =
                new ApplicationCreatedEvent(
                        saved.getApplicationId(),
                        saved.getLeadId(),
                        saved.getCustomerId(),
                        saved.getApplicationNumber(),
                        saved.getLoanProduct(),
                        saved.getLoanAmount(),
                        saved.getLoanTenure(),
                        saved.getInterestRate(),
                        saved.getStatus(),
                        saved.getCreatedAt()
                );

        kafkaProducerService.sendApplicationCreatedEvent(event);

        return mapToResponse(saved);
    }


    // =========================================================
    // UPDATE APPLICATION
    // =========================================================

    @Override
    @Transactional
    public ApplicationResponse updateApplication(
            Long applicationId,
            ApplicationRequest request) {

        Application application =
                findApplication(applicationId);

        application.setLeadId(
                request.getLeadId());

        application.setCustomerId(
                request.getCustomerId());

        application.setLoanProduct(
                request.getLoanProduct());

        application.setLoanAmount(
                request.getLoanAmount());

        application.setLoanTenure(
                request.getLoanTenure());

        application.setInterestRate(
                request.getInterestRate());

        application.setDescription(
                request.getDescription());

        application.setModifiedAt(
                LocalDateTime.now());

        Application updated =
                applicationRepository.save(application);

        return mapToResponse(updated);
    }


    // =========================================================
    // DELETE APPLICATION
    // =========================================================

    @Override
    @Transactional
    public void deleteApplication(
            Long applicationId) {

        Application application =
                findApplication(applicationId);

        applicationRepository.delete(application);
    }


    // =========================================================
    // UPDATE APPLICATION STATUS
    // =========================================================

    @Override
    @Transactional
    public ApplicationResponse updateApplicationStatus(
            Long applicationId,
            ApplicationStatusUpdateRequest request) {

        Application application =
                findApplication(applicationId);

        ApplicationStatus oldStatus =
                application.getStatus();

        ApplicationStatus newStatus =
                request.getStatus();

        // No status change
        if (oldStatus == newStatus) {
            return mapToResponse(application);
        }

        application.setStatus(newStatus);

        application.setModifiedAt(
                LocalDateTime.now());

        Application updated =
                applicationRepository.save(application);


        // =====================================================
        // KAFKA - APPLICATION STATUS CHANGED
        // =====================================================

        ApplicationStatusChangedEvent event =
                new ApplicationStatusChangedEvent(
                        updated.getApplicationId(),
                        updated.getLeadId(),
                        oldStatus,
                        updated.getStatus(),
                        updated.getModifiedAt()
                );

        kafkaProducerService.sendApplicationStatusChangedEvent(
                event
        );

        return mapToResponse(updated);
    }


    // =========================================================
    // GET ALL LOAN PRODUCTS
    // =========================================================

    @Override
    @Transactional
    public List<LoanProductResponse> getAllLoanProducts() {

        return loanProductRepository.findAll()
                .stream()
                .filter(product ->
                        Boolean.TRUE.equals(
                                product.getIsActive())
                                &&
                                !Boolean.TRUE.equals(
                                        product.getIsDeleted()))
                .map(this::toResponse)
                .toList();
    }


    // =========================================================
    // GET LOAN PRODUCT BY ID
    // =========================================================

    @Override
    @Transactional
    public LoanProductResponse getLoanProductById(
            Long productId) {

        LoanProduct product =
                loanProductRepository.findById(productId)
                        .orElseThrow(() ->
                                new RuntimeException(
                                        "Loan product not found: "
                                                + productId
                                )
                        );

        return toResponse(product);
    }


    // =========================================================
    // UPDATE LOAN SPECIFICATION
    // =========================================================

    @Override
    @Transactional
    public ApplicationResponse updateLoanSpecification(
            Long applicationId,
            LoanSpecificationRequest request) {

        Application application =
                findApplication(applicationId);

        application.setLoanProduct(
                request.getLoanProduct());

        application.setLoanAmount(
                request.getLoanAmount());

        application.setLoanTenure(
                request.getLoanTenure());

        application.setInterestRate(
                request.getInterestRate());

        application.setModifiedAt(
                LocalDateTime.now());

        Application updated =
                applicationRepository.save(application);

        return mapToResponse(updated);
    }


    // =========================================================
    // RESUME APPLICATION
    // =========================================================

    @Override
    @Transactional
    public ApplicationResponse resumeApplication(
            Long applicationId) {

        Application application =
                findApplication(applicationId);

        ApplicationStatus oldStatus =
                application.getStatus();

        // Only DRAFT can be resumed
        if (oldStatus != ApplicationStatus.DRAFT) {

            throw new RuntimeException(
                    "Only DRAFT applications can be resumed"
            );
        }

        ApplicationStatus newStatus =
                ApplicationStatus.IN_PROGRESS;

        application.setStatus(newStatus);

        application.setModifiedAt(
                LocalDateTime.now());

        Application updated =
                applicationRepository.save(application);


        // =====================================================
        // KAFKA - APPLICATION STATUS CHANGED
        // =====================================================

        ApplicationStatusChangedEvent event =
                new ApplicationStatusChangedEvent(
                        updated.getApplicationId(),
                        updated.getLeadId(),
                        oldStatus,
                        newStatus,
                        updated.getModifiedAt()
                );

        kafkaProducerService.sendApplicationStatusChangedEvent(
                event
        );

        return mapToResponse(updated);
    }


    // =========================================================
    // GET ALL TASKS
    // =========================================================

    @Override
    @Transactional
    public List<TaskMasterResponse> getAllTasks() {

        return taskMasterRepository.findAll()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }


    // =========================================================
    // GET TASK BY ID
    // =========================================================

    @Override
    @Transactional
    public TaskMasterResponse getTaskById(
            Long taskId) {

        TaskMaster task =
                taskMasterRepository.findById(taskId)
                        .orElseThrow(() ->
                                new RuntimeException(
                                        "Task not found: "
                                                + taskId
                                )
                        );

        return mapToResponse(task);
    }


    // =========================================================
    // GET ALL TASK STAGES
    // =========================================================

    @Override
    @Transactional
    public List<TaskStageMasterResponse> getAllTaskStages() {

        return taskStageMasterRepository.findAll()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }


    // =========================================================
    // GET TASK STAGE BY ID
    // =========================================================

    @Override
    @Transactional
    public TaskStageMasterResponse getTaskStageById(
            Long taskStageId) {

        TaskStageMaster stage =
                taskStageMasterRepository.findById(taskStageId)
                        .orElseThrow(() ->
                                new RuntimeException(
                                        "Task stage not found: "
                                                + taskStageId
                                )
                        );

        return mapToResponse(stage);
    }


    // =========================================================
    // GET ASSIGNMENTS BY APPLICATION ID
    // =========================================================

    @Override
    @Transactional
    public List<ApplicationAssignmentResponse>
    getAssignmentsByApplicationId(
            Long applicationId) {

        // Verify application exists
        findApplication(applicationId);

        return applicationAssignmentRepository
                .findByApplicationId(applicationId)
                .stream()
                .map(this::mapToResponse)
                .toList();
    }


    // =========================================================
    // GET APPLICATION ASSIGNMENT BY ID
    // =========================================================

    @Override
    @Transactional
    public ApplicationAssignmentResponse
    getAssignmentById(
            Long assignmentId) {

        ApplicationAssignment assignment =
                findAssignment(assignmentId);

        return mapToResponse(assignment);
    }


    // =========================================================
    // CREATE APPLICATION ASSIGNMENT
    // =========================================================

    @Override
    @Transactional
    public ApplicationAssignmentResponse createAssignment(
            Long applicationId,
            ApplicationAssignmentRequest request) {

        // Verify application exists
        findApplication(applicationId);

        LocalDateTime now =
                LocalDateTime.now();

        ApplicationAssignment assignment =
                new ApplicationAssignment();

        assignment.setApplicationId(
                applicationId);

        assignment.setAssignedForTaskId(
                request.getAssignedForTaskId());

        assignment.setTaskStageId(
                request.getTaskStageId());

        assignment.setAssignmentStatus(
                request.getAssignmentStatus() != null
                        ? request.getAssignmentStatus()
                        : "ASSIGNED"
        );

        assignment.setAssignmentRemark(
                request.getAssignmentRemark());

        assignment.setProceedToUserId(
                request.getProceedToUserId());

        assignment.setIsTerminal(
                request.getIsTerminal() != null
                        ? request.getIsTerminal()
                        : false
        );

        assignment.setTotalProgress(
                BigDecimal.ZERO);

        assignment.setIsActive(true);

        assignment.setCreatedAt(now);

        assignment.setModifiedAt(now);

        assignment.setCreatedById(101L);

        assignment.setModifiedById(101L);

        assignment.setIsDeleted(false);


        /*
         * assignmentId is generated by PostgreSQL/JPA.
         */

        ApplicationAssignment saved =
                applicationAssignmentRepository.save(
                        assignment);


        // =====================================================
        // KAFKA - APPLICATION ASSIGNMENT CREATED
        // =====================================================

        ApplicationAssignmentCreatedEvent event =
                new ApplicationAssignmentCreatedEvent(
                        saved.getAssignmentId(),
                        saved.getApplicationId(),
                        saved.getAssignedForTaskId(),
                        saved.getTaskStageId(),
                        saved.getAssignmentStatus(),
                        saved.getProceedToUserId(),
                        saved.getCreatedAt()
                );

        kafkaProducerService
                .sendApplicationAssignmentCreated(event);

        return mapToResponse(saved);
    }


    // =========================================================
    // UPDATE APPLICATION ASSIGNMENT STATUS
    // =========================================================

    @Override
    @Transactional
    public ApplicationAssignmentResponse
    updateAssignmentStatus(
            Long assignmentId,
            AssignmentStatusUpdateRequest request) {

        ApplicationAssignment assignment =
                findAssignment(assignmentId);

        String oldStatus =
                assignment.getAssignmentStatus();

        String newStatus =
                request.getStatus();

        // No status change
        if (Objects.equals(oldStatus, newStatus)) {

            if (request.getRemark() != null) {
                assignment.setAssignmentRemark(
                        request.getRemark()
                );

                assignment.setModifiedAt(
                        LocalDateTime.now());

                assignment =
                        applicationAssignmentRepository.save(
                                assignment);
            }

            return mapToResponse(assignment);
        }

        assignment.setAssignmentStatus(newStatus);

        if (request.getRemark() != null) {
            assignment.setAssignmentRemark(
                    request.getRemark()
            );
        }

        assignment.setModifiedAt(
                LocalDateTime.now());

        ApplicationAssignment updated =
                applicationAssignmentRepository.save(
                        assignment);


        // =====================================================
        // KAFKA - ASSIGNMENT STATUS CHANGED
        // =====================================================

        ApplicationAssignmentStatusChangedEvent event =
                new ApplicationAssignmentStatusChangedEvent(
                        updated.getAssignmentId(),
                        updated.getApplicationId(),
                        oldStatus,
                        updated.getAssignmentStatus(),
                        updated.getModifiedAt()
                );

        kafkaProducerService
                .sendApplicationAssignmentStatusChanged(event);

        return mapToResponse(updated);
    }


    // =========================================================
    // FIND APPLICATION
    // =========================================================

    private Application findApplication(
            Long applicationId) {

        return applicationRepository
                .findById(applicationId)
                .orElseThrow(() ->
                        new ApplicationNotFoundException(
                                "Application not found with id: "
                                        + applicationId
                        )
                );
    }


    // =========================================================
    // FIND ASSIGNMENT
    // =========================================================

    private ApplicationAssignment findAssignment(
            Long assignmentId) {

        return applicationAssignmentRepository
                .findById(assignmentId)
                .orElseThrow(() ->
                        new RuntimeException(
                                "Application assignment not found: "
                                        + assignmentId
                        )
                );
    }


    // =========================================================
    // APPLICATION -> RESPONSE
    // =========================================================

    private ApplicationResponse mapToResponse(
            Application application) {

        return new ApplicationResponse(
                application.getApplicationId(),
                application.getLeadId(),
                application.getCustomerId(),
                application.getApplicationNumber(),
                application.getLoanProduct(),
                application.getLoanAmount(),
                application.getLoanTenure(),
                application.getInterestRate(),
                application.getStatus(),
                application.getDescription(),
                application.getCreatedAt(),
                application.getModifiedAt()
        );
    }


    // =========================================================
    // LOAN PRODUCT -> RESPONSE
    // =========================================================

    private LoanProductResponse toResponse(
            LoanProduct product) {

        return new LoanProductResponse(
                product.getProductId(),
                product.getProductName(),
                product.getProductScheme(),
                product.getProductSchemeCode(),
                product.getSubProductId(),
                product.getLoanCategory(),
                product.getMinAmount(),
                product.getMaxAmount(),
                product.getMinTenure(),
                product.getMaxTenure(),
                product.getIsActive()
        );
    }


    // =========================================================
    // TASK -> RESPONSE
    // =========================================================

    private TaskMasterResponse mapToResponse(
            TaskMaster task) {

        return new TaskMasterResponse(
                task.getTaskId(),
                task.getTaskName(),
                task.getTaskDescription(),
                task.getProgress(),
                task.getDeadline(),
                task.getExpectedSubmission(),
                task.getIsActive(),
                task.getCreatedAt(),
                task.getModifiedAt(),
                task.getCreatedById(),
                task.getModifiedById(),
                task.getIsDeleted()
        );
    }


    // =========================================================
    // TASK STAGE -> RESPONSE
    // =========================================================

    private TaskStageMasterResponse mapToResponse(
            TaskStageMaster stage) {

        return new TaskStageMasterResponse(
                stage.getTaskStageId(),
                stage.getStageName(),
                stage.getProgress(),
                stage.getDeadline(),
                stage.getExpectedSubmission(),
                stage.getIsActive(),
                stage.getCreatedAt(),
                stage.getModifiedAt(),
                stage.getCreatedById(),
                stage.getModifiedById(),
                stage.getIsDeleted()
        );
    }


    // =========================================================
    // APPLICATION ASSIGNMENT -> RESPONSE
    // =========================================================

    private ApplicationAssignmentResponse mapToResponse(
            ApplicationAssignment assignment) {

        return new ApplicationAssignmentResponse(
                assignment.getAssignmentId(),
                assignment.getApplicationId(),
                assignment.getAssignedForTaskId(),
                assignment.getTaskStageId(),
                assignment.getAssignmentStatus(),
                assignment.getAssignmentRemark(),
                assignment.getProceedToUserId(),
                assignment.getIsTerminal(),
                assignment.getTotalProgress(),
                assignment.getIsActive(),
                assignment.getCreatedAt(),
                assignment.getModifiedAt(),
                assignment.getVerifiedAt(),
                assignment.getCreatedById(),
                assignment.getModifiedById(),
                assignment.getVerifiedById(),
                assignment.getVerificationMode(),
                assignment.getIsDeleted()
        );
    }
}