package com.los.applicationservice.service.serviceImpl;

import com.los.applicationservice.dto.*;
import com.los.applicationservice.exception.ApplicationNotFoundException;
import com.los.applicationservice.kafka.KafkaProducerService;
import com.los.applicationservice.kafka.event.LeadCreatedEvent;
import com.los.applicationservice.model.ApplicationStatus;
import com.los.applicationservice.model.Lead;
import com.los.applicationservice.model.LeadActivity;
import com.los.applicationservice.model.LeadAssignment;
import com.los.applicationservice.repository.LeadActivityRepository;
import com.los.applicationservice.repository.LeadAssignmentRepository;
import com.los.applicationservice.repository.LeadRepository;
import com.los.applicationservice.service.LeadService;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;

@Service
@RequiredArgsConstructor
public class LeadServiceImpl implements LeadService {

    private final LeadRepository leadRepository;

    private final LeadAssignmentRepository leadAssignmentRepository;

    private final LeadActivityRepository leadActivityRepository;

    private final KafkaProducerService kafkaProducerService;


    // =========================================================
    // GET ALL LEADS
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public List<LeadResponse> getAllLeads() {

        return leadRepository.findAll()
                .stream()
                .map(this::mapToResponse)
                .toList();
    }


    // =========================================================
    // GET LEAD BY ID
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public LeadResponse getLeadById(Long leadId) {

        Lead lead = findLead(leadId);

        return mapToResponse(lead);
    }


    // =========================================================
    // CREATE LEAD
    // =========================================================

    @Override
    @Transactional
    public LeadResponse createLead(LeadRequest request) {

        LocalDateTime now = LocalDateTime.now();

        Lead lead = new Lead();

        lead.setSourceName(
                request.getSourceName()
        );

        lead.setChannelType(
                request.getChannelType()
        );

        lead.setMobile(
                request.getMobile()
        );

        lead.setPan(
                request.getPan()
        );

        lead.setDob(
                request.getDob()
        );

        lead.setDescription(
                request.getDescription()
        );

        // Initial status
        lead.setStatus(
                ApplicationStatus.NEW
        );

        // System fields
        lead.setIsActive(true);
        lead.setIsDeleted(false);
        lead.setCreatedAt(now);
        lead.setModifiedAt(now);

        // Temporary logged-in user
        lead.setCreatedById(101L);
        lead.setModifiedById(101L);

        /*
         * Save to PostgreSQL.
         *
         * leadId is generated by JPA/PostgreSQL.
         */
        Lead savedLead =
                leadRepository.save(lead);


        // =====================================================
        // TRACKING
        // =====================================================

        addTracking(
                savedLead.getLeadId(),
                ApplicationStatus.NEW,
                "Lead created"
        );


        // =====================================================
        // KAFKA EVENT
        // =====================================================

        LeadCreatedEvent event =
                new LeadCreatedEvent(
                        savedLead.getLeadId(),
                        savedLead.getSourceName(),
                        savedLead.getChannelType(),
                        savedLead.getMobile(),
                        savedLead.getPan(),
                        savedLead.getDob(),
                        savedLead.getStatus(),
                        savedLead.getDescription()
                );

        kafkaProducerService.sendLeadCreated(
                savedLead.getLeadId(),
                event
        );

        return mapToResponse(savedLead);
    }


    // =========================================================
    // UPDATE LEAD
    // =========================================================

    @Override
    @Transactional
    public LeadResponse updateLead(
            Long leadId,
            LeadRequest request) {

        Lead existingLead =
                findLead(leadId);

        existingLead.setSourceName(
                request.getSourceName()
        );

        existingLead.setChannelType(
                request.getChannelType()
        );

        existingLead.setMobile(
                request.getMobile()
        );

        existingLead.setPan(
                request.getPan()
        );

        existingLead.setDob(
                request.getDob()
        );

        existingLead.setDescription(
                request.getDescription()
        );

        existingLead.setModifiedAt(
                LocalDateTime.now()
        );

        existingLead.setModifiedById(
                101L
        );

        Lead updatedLead =
                leadRepository.save(existingLead);

        return mapToResponse(updatedLead);
    }


    // =========================================================
    // DELETE LEAD
    // =========================================================

    @Override
    @Transactional
    public void deleteLead(Long leadId) {

        Lead existingLead =
                findLead(leadId);

        /*
         * Hard delete.
         *
         * If you want soft delete instead,
         * we can change this later.
         */
        leadRepository.delete(existingLead);
    }


    // =========================================================
    // UPDATE LEAD STATUS
    // =========================================================

    @Override
    @Transactional
    public LeadResponse updateLeadStatus(
            Long leadId,
            ApplicationStatusUpdateRequest request) {

        Lead lead =
                findLead(leadId);

        ApplicationStatus oldStatus =
                lead.getStatus();

        ApplicationStatus newStatus =
                request.getStatus();


        // =====================================================
        // VALIDATE STATUS
        // =====================================================

        validateStatusTransition(
                oldStatus,
                newStatus
        );


        // =====================================================
        // UPDATE STATUS
        // =====================================================

        lead.setStatus(newStatus);

        lead.setModifiedAt(
                LocalDateTime.now()
        );

        lead.setModifiedById(
                101L
        );

        Lead updatedLead =
                leadRepository.save(lead);


        // =====================================================
        // TRACKING
        // =====================================================

        String remarks =
                "Lead status changed from "
                        + oldStatus
                        + " to "
                        + newStatus;

        addTracking(
                updatedLead.getLeadId(),
                newStatus,
                remarks
        );


        // =====================================================
        // KAFKA EVENT
        // =====================================================

        LeadCreatedEvent event =
                new LeadCreatedEvent(
                        updatedLead.getLeadId(),
                        updatedLead.getSourceName(),
                        updatedLead.getChannelType(),
                        updatedLead.getMobile(),
                        updatedLead.getPan(),
                        updatedLead.getDob(),
                        updatedLead.getStatus(),
                        updatedLead.getDescription()
                );

        kafkaProducerService.sendLeadCreated(
                updatedLead.getLeadId(),
                event
        );

        return mapToResponse(updatedLead);
    }


    // =========================================================
    // GET LEAD TRACKING
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public List<LeadTrackingResponse> getLeadTracking(
            Long leadId) {

        // Make sure lead exists
        findLead(leadId);

        return leadActivityRepository
                .findByLeadIdOrderByCreatedAtAsc(leadId)
                .stream()
                .map(this::mapActivityToResponse)
                .toList();
    }


    // =========================================================
    // FIND LEAD
    // =========================================================

    private Lead findLead(Long leadId) {

        return leadRepository
                .findById(leadId)
                .orElseThrow(
                        () -> new ApplicationNotFoundException(
                                "Lead not found with id: "
                                        + leadId
                        )
                );
    }


    // =========================================================
    // ADD TRACKING
    // =========================================================

    private void addTracking(
            Long leadId,
            ApplicationStatus status,
            String remarks) {

        LeadActivity activity =
                new LeadActivity();

        activity.setLeadId(leadId);

        activity.setAction(
                "STATUS_CHANGE"
        );

        activity.setOldStatus(null);

        activity.setNewStatus(status);

        activity.setRemarks(remarks);

        activity.setCreatedAt(
                LocalDateTime.now()
        );

        leadActivityRepository.save(activity);
    }


    // =========================================================
    // STATUS TRANSITION VALIDATION
    // =========================================================

    private void validateStatusTransition(
            ApplicationStatus oldStatus,
            ApplicationStatus newStatus) {

        if (oldStatus == newStatus) {

            throw new IllegalArgumentException(
                    "Lead is already in status: "
                            + newStatus
            );
        }

        /*
         * For now all different transitions
         * are allowed.
         */
    }


    // =========================================================
    // ENTITY -> RESPONSE
    // =========================================================

    private LeadResponse mapToResponse(
            Lead lead) {

        return new LeadResponse(
                lead.getLeadId(),
                lead.getSourceName(),
                lead.getChannelType(),
                lead.getMobile(),
                lead.getPan(),
                lead.getDob(),
                lead.getStatus(),
                lead.getDescription(),
                lead.getIsActive(),
                lead.getCreatedAt(),
                lead.getModifiedAt(),
                lead.getCreatedById(),
                lead.getModifiedById(),
                lead.getIsDeleted()
        );
    }


    // =========================================================
    // ACTIVITY -> TRACKING RESPONSE
    // =========================================================

    private LeadTrackingResponse mapActivityToResponse(
            LeadActivity activity) {

        return new LeadTrackingResponse(
                activity.getLeadId(),
                activity.getNewStatus(),
                activity.getCreatedAt(),
                activity.getRemarks()
        );
    }


    // =========================================================
    // GET ALL ASSIGNMENTS
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public List<LeadAssignmentResponse> getAllAssignments() {

        return leadAssignmentRepository
                .findAll()
                .stream()
                .map(this::toResponse)
                .toList();
    }


    // =========================================================
    // GET ASSIGNMENTS BY LEAD ID
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public List<LeadAssignmentResponse> getAssignmentsByLeadId(
            Long leadId) {

        findLead(leadId);

        return leadAssignmentRepository
                .findByLeadId(leadId)
                .stream()
                .map(this::toResponse)
                .toList();
    }


    // =========================================================
    // GET ASSIGNMENT BY ID
    // =========================================================

    @Override
    @Transactional(readOnly = true)
    public LeadAssignmentResponse getAssignmentById(
            Long assignmentId) {

        LeadAssignment assignment =
                findAssignment(assignmentId);

        return toResponse(assignment);
    }


    // =========================================================
    // CREATE ASSIGNMENT
    // =========================================================

    @Override
    @Transactional
    public LeadAssignmentResponse createAssignment(
            Long leadId,
            LeadAssignmentRequest request) {

        // Make sure lead exists
        findLead(leadId);

        LocalDateTime now =
                LocalDateTime.now();

        LeadAssignment assignment =
                new LeadAssignment();

        assignment.setLeadId(leadId);

        assignment.setAssignedForTaskId(
                request.getAssignedForTaskId()
        );

        assignment.setAssignmentStatus(
                request.getAssignmentStatus()
        );

        assignment.setAssignmentRemark(
                request.getAssignmentRemark()
        );

        assignment.setProceedToId(
                request.getProceedToId()
        );

        assignment.setIsTerminal(
                request.getIsTerminal()
        );

        assignment.setIsActive(true);

        assignment.setCreatedAt(now);

        assignment.setModifiedAt(now);

        assignment.setCreatedById(101L);

        assignment.setModifiedById(101L);

        assignment.setIsDeleted(false);

        /*
         * assignmentId is generated by JPA/PostgreSQL.
         */
        LeadAssignment savedAssignment =
                leadAssignmentRepository.save(
                        assignment
                );

        return toResponse(savedAssignment);
    }


    // =========================================================
    // UPDATE ASSIGNMENT
    // =========================================================

    @Override
    @Transactional
    public LeadAssignmentResponse updateAssignment(
            Long assignmentId,
            LeadAssignmentRequest request) {

        LeadAssignment assignment =
                findAssignment(assignmentId);

        assignment.setAssignedForTaskId(
                request.getAssignedForTaskId()
        );

        assignment.setAssignmentStatus(
                request.getAssignmentStatus()
        );

        assignment.setAssignmentRemark(
                request.getAssignmentRemark()
        );

        assignment.setProceedToId(
                request.getProceedToId()
        );

        assignment.setIsTerminal(
                request.getIsTerminal()
        );

        assignment.setModifiedAt(
                LocalDateTime.now()
        );

        assignment.setModifiedById(101L);

        LeadAssignment updatedAssignment =
                leadAssignmentRepository.save(
                        assignment
                );

        return toResponse(updatedAssignment);
    }


    // =========================================================
    // DELETE ASSIGNMENT
    // =========================================================

    @Override
    @Transactional
    public void deleteAssignment(
            Long assignmentId) {

        LeadAssignment assignment =
                findAssignment(assignmentId);

        /*
         * Soft delete.
         */
        assignment.setIsDeleted(true);

        assignment.setIsActive(false);

        assignment.setModifiedAt(
                LocalDateTime.now()
        );

        assignment.setModifiedById(101L);

        leadAssignmentRepository.save(
                assignment
        );
    }


    // =========================================================
    // FIND ASSIGNMENT
    // =========================================================

    private LeadAssignment findAssignment(
            Long assignmentId) {

        return leadAssignmentRepository
                .findById(assignmentId)
                .orElseThrow(
                        () -> new RuntimeException(
                                "Lead assignment not found: "
                                        + assignmentId
                        )
                );
    }


    // =========================================================
    // CONVERT MODEL -> RESPONSE DTO
    // =========================================================

    private LeadAssignmentResponse toResponse(
            LeadAssignment assignment) {

        return new LeadAssignmentResponse(
                assignment.getAssignmentId(),
                assignment.getLeadId(),
                assignment.getAssignedForTaskId(),
                assignment.getAssignmentStatus(),
                assignment.getAssignmentRemark(),
                assignment.getProceedToId(),
                assignment.getIsTerminal(),
                assignment.getIsActive(),
                assignment.getCreatedAt(),
                assignment.getModifiedAt(),
                assignment.getVerifiedAt(),
                assignment.getCreatedById(),
                assignment.getModifiedById(),
                assignment.getVerifiedById(),
                assignment.getVerificationMode(),
                assignment.getIsDeleted()
        );
    }
}