spring:
  application:
    name: apigateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: authservice
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**

            - id: salesservice
              uri: http://localhost:8082
              predicates:
                - Path=/api/applications/**

            - id: documentservice
              uri: http://localhost:8083
              predicates:
                - Path=/api/documents/**,/api/document-types/**

server:
  port: 8080

jwt:
  secret: my-super-secret-key-for-los-system-2026
