spring:
  application:
    name: documentservice
server:
  port: 8083

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

document:
  storage:
    directory: docs
